### ISSUE TITLE
Nullpointer exception

### ISSUE THREAD

**Issue by Mierdin** [nre-learning/antidote-web#11]
```
root@antidote-web-74cf978ffc-tmc7l:/opt/guacamole# cat /usr/local/tomcat/logs/localhost.2018-10-14.log
14-Oct-2018 19:35:06.460 SEVERE [http-nio-8080-exec-1004] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.service() for servlet [Tunnel] in context with path [] threw exception
 java.lang.NullPointerException
	at org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect(GuacamoleTunnelServlet.java:42)
	at org.apache.guacamole.servlet.GuacamoleHTTPTunnelServlet.handleTunnelRequest(GuacamoleHTTPTunnelServlet.java:213)
	at org.apache.guacamole.servlet.GuacamoleHTTPTunnelServlet.doGet(GuacamoleHTTPTunnelServlet.java:137)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:516)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1086)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:659)
	at org.apache.coyote.http11.Http11NioProtocol$Http11ConnectionHandler.process(Http11NioProtocol.java:223)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1558)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1515)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```

Might be related to the stdout of the container, showing strange null values:

```
14-Oct-2018 19:28:20.036 INFO [http-nio-8080-exec-979] null.null Configuring Guacamole tunnel
14-Oct-2018 19:28:20.037 INFO [http-nio-8080-exec-979] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Incoming device port: 22
14-Oct-2018 19:28:20.045 INFO [http-nio-8080-exec-1007] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: 10.100.103.154;22;922;493;root;VR-netlab9
14-Oct-2018 19:28:20.045 INFO [http-nio-8080-exec-1007] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Configuring Guacamole tunnel
14-Oct-2018 19:28:20.045 INFO [http-nio-8080-exec-1007] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Incoming device port: 22
14-Oct-2018 19:34:04.114 INFO [http-nio-8080-exec-1021] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: 10.101.33.69;22;922;493;antidote;antidotepassword
14-Oct-2018 19:34:04.114 INFO [http-nio-8080-exec-1017] null.null Raw connect data: 10.106.48.207;22;922;493;root;VR-netlab9
14-Oct-2018 19:34:04.114 INFO [http-nio-8080-exec-1015] null.null Raw connect data: 10.103.170.18;22;922;493;root;VR-netlab9
14-Oct-2018 19:34:04.115 INFO [http-nio-8080-exec-1017] null.null Configuring Guacamole tunnel
14-Oct-2018 19:34:04.115 INFO [http-nio-8080-exec-1015] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Configuring Guacamole tunnel
14-Oct-2018 19:34:04.115 INFO [http-nio-8080-exec-1015] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Incoming device port: 22
14-Oct-2018 19:34:04.115 INFO [http-nio-8080-exec-1021] null.null Configuring Guacamole tunnel
14-Oct-2018 19:34:04.115 INFO [http-nio-8080-exec-1017] null.null Incoming device port: 22
14-Oct-2018 19:34:04.115 INFO [http-nio-8080-exec-1021] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Incoming device port: 22
14-Oct-2018 19:34:04.123 INFO [http-nio-8080-exec-1011] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: 10.100.103.154;22;922;493;root;VR-netlab9
14-Oct-2018 19:34:04.123 INFO [http-nio-8080-exec-1011] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Configuring Guacamole tunnel
14-Oct-2018 19:34:04.123 INFO [http-nio-8080-exec-1011] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Incoming device port: 22
14-Oct-2018 19:35:06.459 INFO [http-nio-8080-exec-1004] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: null
14-Oct-2018 19:37:26.706 INFO [http-nio-8080-exec-1004] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: null
14-Oct-2018 19:37:26.874 INFO [http-nio-8080-exec-1013] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: null
14-Oct-2018 19:37:38.668 INFO [http-nio-8080-exec-1000] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: 10.100.123.43;22;922;493;antidote;antidotepassword
14-Oct-2018 19:37:38.669 INFO [http-nio-8080-exec-1000] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Configuring Guacamole tunnel
14-Oct-2018 19:37:38.669 INFO [http-nio-8080-exec-1000] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Incoming device port: 22
14-Oct-2018 19:37:38.676 INFO [http-nio-8080-exec-999] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: 10.97.168.139;22;922;493;root;VR-netlab9
14-Oct-2018 19:37:38.676 INFO [http-nio-8080-exec-999] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Configuring Guacamole tunnel
14-Oct-2018 19:37:38.676 INFO [http-nio-8080-exec-999] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Incoming device port: 22
14-Oct-2018 19:37:38.686 INFO [http-nio-8080-exec-1017] org.apache.guacamole.net.antidote.GuacamoleTunnelServlet.doConnect Raw connect data: 10.97.180.48;22;922;493;root;VR-netlab9
```

**Comment by Mierdin** [comment]
Haven't been able to see this happen again recently, so removing it from 0.2.0, will follow up later

**Comment by Mierdin** [comment]
Guacamole is gone, so closing this.
